udo: false
language: python
python:
    - "2.7"
    - "3.4"
env: 
    - TEST_SUITE='coverage run setup.py test'
    - TEST_SUITE='flake8 --exclude=venv,setup.py'
install: "pip install -r requirements.txt"
script: 
    - echo $TEST_SUITE
    - $TEST_SUITE
affter_success: 
    - coverage report
    - coveralls
